[package]
name = "system-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
sysinfo = "0.24"  # Adjust to the latest version if necessary
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
